import React from 'react';
import { motion } from 'framer-motion';
import { FileProtectOutlined, SafetyCertificateOutlined, ReadOutlined } from '@ant-design/icons';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const TermsPage = () => {
  return (
    <div className="min-h-screen">
      <Navbar />
      <div className="min-h-screen bg-[#fcfcfe] pt-32 pb-24 px-6">
      <div className="max-w-4xl mx-auto">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-16"
        >
          <div className="inline-block p-4 rounded-[24px] bg-primary-50 text-primary-600 mb-6">
            <FileProtectOutlined className="text-4xl" />
          </div>
          <h1 className="text-5xl md:text-6xl font-black text-gray-900 mb-6 tracking-tight">Terms & Conditions</h1>
          <p className="text-gray-500 text-lg">Last updated: May 2026</p>
        </motion.div>

        <div className="bg-white rounded-[48px] p-8 md:p-16 border border-purple-50 shadow-2xl shadow-purple-100/50 space-y-12">
          <section>
            <h2 className="text-2xl font-black text-gray-900 mb-6 flex items-center gap-3">
              <span className="w-8 h-8 rounded-xl bg-primary-100 text-primary-600 flex items-center justify-center text-sm">1</span>
              Acceptance of Terms
            </h2>
            <p className="text-gray-600 leading-relaxed">
              By accessing and using Vichaar, you agree to be bound by these Terms and Conditions. Our platform provides AI-powered tools for content creation and management. You must be at least 18 years old to use this service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-gray-900 mb-6 flex items-center gap-3">
              <span className="w-8 h-8 rounded-xl bg-purple-100 text-purple-600 flex items-center justify-center text-sm">2</span>
              User Responsibilities
            </h2>
            <p className="text-gray-600 leading-relaxed">
              Users are responsible for the content they publish. While our AI assistants help in drafting and optimization, the final accuracy and ethical compliance of the content rest with the author. Spamming, plagiarism, or harassment is strictly prohibited.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-gray-900 mb-6 flex items-center gap-3">
              <span className="w-8 h-8 rounded-xl bg-indigo-100 text-indigo-600 flex items-center justify-center text-sm">3</span>
              Premium Subscriptions
            </h2>
            <p className="text-gray-600 leading-relaxed">
              Vichaar Pro offers advanced AI features. Subscription payments are handled via Razorpay. Users can cancel their subscriptions at any time through their dashboard settings. Access to premium features will continue until the end of the current billing cycle.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-gray-900 mb-6 flex items-center gap-3">
              <span className="w-8 h-8 rounded-xl bg-pink-100 text-pink-600 flex items-center justify-center text-sm">4</span>
              AI Content Policy
            </h2>
            <p className="text-gray-600 leading-relaxed">
              Content generated by our AI is meant for creative assistance. We do not claim ownership over your AI-assisted works. However, you must not use our AI to generate malicious code, disinformation, or sexually explicit material.
            </p>
          </section>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default TermsPage;
